/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlmanacRouteImport } from './routes/almanac'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as DiaryRouteImport } from './routes/diary'
import { Route as DumpRouteImport } from './routes/dump'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TimetableRouteImport } from './routes/timetable'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmanacRoute = AlmanacRouteImport.update({
  id: '/almanac',
  path: '/almanac',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaryRoute = DiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => rootRouteImport,
} as any)
const DumpRoute = DumpRouteImport.update({
  id: '/dump',
  path: '/dump',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/almanac': typeof AlmanacRoute
  '/daily': typeof DailyRoute
  '/diary': typeof DiaryRoute
  '/dump': typeof DumpRoute
  '/settings': typeof SettingsRoute
  '/timetable': typeof TimetableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/almanac': typeof AlmanacRoute
  '/daily': typeof DailyRoute
  '/diary': typeof DiaryRoute
  '/dump': typeof DumpRoute
  '/settings': typeof SettingsRoute
  '/timetable': typeof TimetableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/almanac': typeof AlmanacRoute
  '/daily': typeof DailyRoute
  '/diary': typeof DiaryRoute
  '/dump': typeof DumpRoute
  '/settings': typeof SettingsRoute
  '/timetable': typeof TimetableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/almanac'
    | '/daily'
    | '/diary'
    | '/dump'
    | '/settings'
    | '/timetable'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/almanac'
    | '/daily'
    | '/diary'
    | '/dump'
    | '/settings'
    | '/timetable'
  id:
    | '__root__'
    | '/'
    | '/almanac'
    | '/daily'
    | '/diary'
    | '/dump'
    | '/settings'
    | '/timetable'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlmanacRoute: typeof AlmanacRoute
  DailyRoute: typeof DailyRoute
  DiaryRoute: typeof DiaryRoute
  DumpRoute: typeof DumpRoute
  SettingsRoute: typeof SettingsRoute
  TimetableRoute: typeof TimetableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almanac': {
      id: '/almanac'
      path: '/almanac'
      fullPath: '/almanac'
      preLoaderRoute: typeof AlmanacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diary': {
      id: '/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof DiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dump': {
      id: '/dump'
      path: '/dump'
      fullPath: '/dump'
      preLoaderRoute: typeof DumpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlmanacRoute: AlmanacRoute,
  DailyRoute: DailyRoute,
  DiaryRoute: DiaryRoute,
  DumpRoute: DumpRoute,
  SettingsRoute: SettingsRoute,
  TimetableRoute: TimetableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
